/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Datos.vperfume;
import java.awt.event.*;
/**
 *
 * @author Paola
 */
public class frmconsultar extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarPerfume
     */
    
    
    
    public frmconsultar() {
        initComponents();
        combonombre();
        inhabilitar();
    }
    
    //metodo que no permite editar datos de los JTextField 
    private void inhabilitar(){
        txtprecio.setEnabled(false);
        txtcontenido.setEnabled(false);
        txtlanzamiento.setEnabled(false);
        txtcasa.setEnabled(false);
    }
    
    //muestra por defecto datos en la primera casilla comboBox
    private void combonombre(){
        //declaracionvariables cons=new declaracionvariables();
        cbxnombre.addItem(vperfume.nombre0);
        cbxnombre.addItem(vperfume.nombre1);
        cbxnombre.addItem(vperfume.nombre2);
        cbxnombre.addItem(vperfume.nombre3);
        cbxnombre.addItem(vperfume.nombre4);
    }
    
    private void categoria(){
        txtprecio.setText(String.valueOf(vperfume.precio0));
        txtcontenido.setText(String.valueOf(vperfume.contenido0));
        txtlanzamiento.setText(String.valueOf(vperfume.año0));
        txtcasa.setText(vperfume.casa0);
    }
    
    private void categoriaUno(){
        txtprecio.setText(String.valueOf(vperfume.precio1));
        txtcontenido.setText(String.valueOf(vperfume.contenido1));
        txtlanzamiento.setText(String.valueOf(vperfume.año1));
        txtcasa.setText(vperfume.casa1);
    }
    
    private void categoriaDos(){
        txtprecio.setText(String.valueOf(vperfume.precio2));
        txtcontenido.setText(String.valueOf(vperfume.contenido2));
        txtlanzamiento.setText(String.valueOf(vperfume.año2));
        txtcasa.setText(vperfume.casa1);
    }
    
    private void categoriaTres(){
        txtprecio.setText(String.valueOf(vperfume.precio3));
        txtcontenido.setText(String.valueOf(vperfume.contenido3));
        txtlanzamiento.setText(String.valueOf(vperfume.año3));
        txtcasa.setText(vperfume.casa1);
    }
    
    private void categoriaCuatro(){
        txtprecio.setText(String.valueOf(vperfume.precio4));
        txtcontenido.setText(String.valueOf(vperfume.contenido4));
        txtlanzamiento.setText(String.valueOf(vperfume.año4));
        txtcasa.setText(vperfume.casa1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new java.awt.Label();
        añolanzamiento = new java.awt.Label();
        precio = new java.awt.Label();
        contenido1 = new java.awt.Label();
        casa = new java.awt.Label();
        cbxnombre = new javax.swing.JComboBox<>();
        btncerrar = new javax.swing.JButton();
        txtprecio = new javax.swing.JTextField();
        txtcontenido = new javax.swing.JTextField();
        txtlanzamiento = new javax.swing.JTextField();
        txtcasa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.setText("Nombre");

        añolanzamiento.setText("Año de Lanzamiento");

        precio.setText("Precio (S/)");

        contenido1.setText("Contenido (ml)");

        casa.setText("Casa");

        cbxnombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxnombreItemStateChanged(evt);
            }
        });

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añolanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(btncerrar)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxnombre, 0, 116, Short.MAX_VALUE)
                            .addComponent(txtprecio)
                            .addComponent(txtcontenido)
                            .addComponent(txtlanzamiento)
                            .addComponent(txtcasa))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btncerrar)
                                        .addComponent(cbxnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añolanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(java.awt.event.ActionEvent evt) { 
        
    }
    private void cbxnombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxnombreItemStateChanged
        int opcion = cbxnombre.getSelectedIndex();
         
         switch(opcion){
             case 0: categoria(); break;
             case 1: categoriaUno(); break;
             case 2: categoriaDos(); break;
             case 3: categoriaTres(); break;
             case 4: categoriaCuatro(); break;
             //default: categoria();
         }
    }//GEN-LAST:event_cbxnombreItemStateChanged

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmconsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmconsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmconsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmconsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmconsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label añolanzamiento;
    private javax.swing.JButton btncerrar;
    private java.awt.Label casa;
    private javax.swing.JComboBox<String> cbxnombre;
    private java.awt.Label contenido1;
    private java.awt.Label nombre;
    private java.awt.Label precio;
    private javax.swing.JTextField txtcasa;
    private javax.swing.JTextField txtcontenido;
    private javax.swing.JTextField txtlanzamiento;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
