/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Paola
 */
public class frminicio extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frminicio() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menusalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuConsultar = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuDescuentos = new javax.swing.JMenuItem();
        menuObsequio = new javax.swing.JMenuItem();
        menuOptima = new javax.swing.JMenuItem();
        menuSorpresa = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuAcerca = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Archivo");

        menusalir.setText("Salir");
        menusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalirActionPerformed(evt);
            }
        });
        jMenu3.add(menusalir);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Mantenimiento");

        menuConsultar.setText("Consultar perfume");
        menuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarActionPerformed(evt);
            }
        });
        jMenu4.add(menuConsultar);

        menuModificar.setText("Modificar perfume");
        menuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarActionPerformed(evt);
            }
        });
        jMenu4.add(menuModificar);

        menuListar.setText("Listar Perfume");
        menuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarActionPerformed(evt);
            }
        });
        jMenu4.add(menuListar);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ventas");

        jMenuItem5.setText("Vender");
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Generar reportes");
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Configuracion");

        menuDescuentos.setText("Configurar descuentos");
        menuDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDescuentosActionPerformed(evt);
            }
        });
        jMenu7.add(menuDescuentos);

        menuObsequio.setText("Configurar obsequio");
        menuObsequio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObsequioActionPerformed(evt);
            }
        });
        jMenu7.add(menuObsequio);

        menuOptima.setText("Configurar cantidad optima de perfumes vendidos");
        menuOptima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptimaActionPerformed(evt);
            }
        });
        jMenu7.add(menuOptima);

        menuSorpresa.setText("Configurar premio sorpresa");
        menuSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSorpresaActionPerformed(evt);
            }
        });
        jMenu7.add(menuSorpresa);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Ayuda");

        menuAcerca.setText("Acerca de tienda");
        menuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaActionPerformed(evt);
            }
        });
        jMenu5.add(menuAcerca);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificarActionPerformed
        // TODO add your handling code here:
        frmmodificar modificar=new frmmodificar();
        modificar.setVisible(true);
    }//GEN-LAST:event_menuModificarActionPerformed

    private void menusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalirActionPerformed
        // TODO add your handling code here:        
        System.exit(0);
    }//GEN-LAST:event_menusalirActionPerformed

    private void menuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarActionPerformed
        // TODO add your handling code here:
        frmconsultar consultar=new frmconsultar(); 
        consultar.setVisible(true);
        
    }//GEN-LAST:event_menuConsultarActionPerformed

    private void menuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarActionPerformed
        // TODO add your handling code here:
        frmlistar listar = new frmlistar();
        listar.setVisible(true);
    }//GEN-LAST:event_menuListarActionPerformed

    private void menuDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDescuentosActionPerformed
        // TODO add your handling code here:
        frmdescuentos descuentos = new frmdescuentos();
        descuentos.setVisible(true);
    }//GEN-LAST:event_menuDescuentosActionPerformed

    private void menuObsequioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObsequioActionPerformed
        // TODO add your handling code here:
        frmobsequio obsequio = new frmobsequio();
        obsequio.setVisible(true);
    }//GEN-LAST:event_menuObsequioActionPerformed

    private void menuOptimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptimaActionPerformed
        // TODO add your handling code here:
        frmoptima optimo = new frmoptima();
        optimo.setVisible(true);
    }//GEN-LAST:event_menuOptimaActionPerformed

    private void menuSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSorpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSorpresaActionPerformed

    private void menuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaActionPerformed
        // TODO add your handling code here:
        frmacerca acerca = new frmacerca();
        acerca.setVisible(true);
    }//GEN-LAST:event_menuAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frminicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuAcerca;
    private javax.swing.JMenuItem menuConsultar;
    private javax.swing.JMenuItem menuDescuentos;
    private javax.swing.JMenuItem menuListar;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JMenuItem menuObsequio;
    private javax.swing.JMenuItem menuOptima;
    private javax.swing.JMenuItem menuSorpresa;
    private javax.swing.JMenuItem menusalir;
    // End of variables declaration//GEN-END:variables
}
