/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.DefaultListModel;
import Datos.vperfume;
/**
 *
 * @author angelgc
 */
public class frmlistar extends javax.swing.JFrame {

    /**
     * Creates new form frmlistar
     */
    DefaultListModel JLista = new DefaultListModel();
    
    public frmlistar() {
        initComponents();
        JListaDatos.setModel(JLista);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JListaDatos = new javax.swing.JList<>();
        btncerrar = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JListaDatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Listado de Perfumes", " ", "Nombre\t\t:", "Precio\t\t:", "Año Lanzamiento\t:", "Casa\t\t:", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JListaDatos.setToolTipText("");
        jScrollPane1.setViewportView(JListaDatos);

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnlistar.setText("Listar");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btncerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnlistar)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncerrar)
                    .addComponent(btnlistar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
       JLista.addElement("Listado de Perfumes");
       JLista.addElement("\n \n");
       JLista.addElement("Nombre   :" + vperfume.nombre0);
       JLista.addElement("Precio   :" + vperfume.precio0);
       JLista.addElement("Contenido    :" + vperfume.contenido0);
       JLista.addElement("Año de lanzamiento   :" + vperfume.año0);
       JLista.addElement("Casa :" + vperfume.casa0);
       
       JLista.addElement("\n \n \n");
       JLista.addElement("Nombre   :" + vperfume.nombre1);
       JLista.addElement("Precio   :" + vperfume.precio1);
       JLista.addElement("Contenido    :" + vperfume.contenido1);
       JLista.addElement("Año de lanzamiento   :" + vperfume.año1);
       JLista.addElement("Casa :" + vperfume.casa1);
       
       JLista.addElement("\n \n \n");
       JLista.addElement("Nombre   :" + vperfume.nombre2);
       JLista.addElement("Precio   :" + vperfume.precio2);
       JLista.addElement("Contenido    :" + vperfume.contenido2);
       JLista.addElement("Año de lanzamiento   :" + vperfume.año2);
       JLista.addElement("Casa :" + vperfume.casa2);
       
       JLista.addElement("\n \n \n");
       JLista.addElement("Nombre   :" + vperfume.nombre3);
       JLista.addElement("Precio   :" + vperfume.precio3);
       JLista.addElement("Contenido    :" + vperfume.contenido3);
       JLista.addElement("Año de lanzamiento   :" + vperfume.año3);
       JLista.addElement("Casa :" + vperfume.casa3);
       
       JLista.addElement("\n \n \n");
       JLista.addElement("Nombre   :" + vperfume.nombre4);
       JLista.addElement("Precio   :" + vperfume.precio4);
       JLista.addElement("Contenido    :" + vperfume.contenido4);
       JLista.addElement("Año de lanzamiento   :" + vperfume.año4);
       JLista.addElement("Casa :" + vperfume.casa4);
       
       //txtresultado.setText(String.valueOf(vperfume.getPrecio0()));
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmlistar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListaDatos;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
