/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Datos.vperfume;
/**
 *
 * @author Paola
 */
public class frmmodificar extends javax.swing.JFrame {    

    public double precio0;
    /**
     * Creates new form ModificarPerfume
     */
    public frmmodificar() {
        initComponents();
        combonombre();
    }
    
    private void combonombre(){
        //declaracionvariables cons=new declaracionvariables();
        cbxnombre.addItem(vperfume.nombre0);
        cbxnombre.addItem(vperfume.nombre1);
        cbxnombre.addItem(vperfume.nombre2);
        cbxnombre.addItem(vperfume.nombre3);
        cbxnombre.addItem(vperfume.nombre4);
    }
    
    private void categoria(){
        txtprecio.setText(String.valueOf(vperfume.precio0));
        txtcontenido.setText(String.valueOf(vperfume.contenido0));
        txtlanzamiento.setText(String.valueOf(vperfume.año0));
        txtcasa.setText(vperfume.casa0);
    }
    
    private void categoriaUno(){
        txtprecio.setText(String.valueOf(vperfume.precio1));
        txtcontenido.setText(String.valueOf(vperfume.contenido1));
        txtlanzamiento.setText(String.valueOf(vperfume.año1));
        txtcasa.setText(vperfume.casa1);
    }
    
    private void categoriaDos(){
        txtprecio.setText(String.valueOf(vperfume.precio2));
        txtcontenido.setText(String.valueOf(vperfume.contenido2));
        txtlanzamiento.setText(String.valueOf(vperfume.año2));
        txtcasa.setText(vperfume.casa1);
    }
    
    private void categoriaTres(){
        txtprecio.setText(String.valueOf(vperfume.precio3));
        txtcontenido.setText(String.valueOf(vperfume.contenido3));
        txtlanzamiento.setText(String.valueOf(vperfume.año3));
        txtcasa.setText(vperfume.casa1);
    }
    
    private void categoriaCuatro(){
        txtprecio.setText(String.valueOf(vperfume.precio4));
        txtcontenido.setText(String.valueOf(vperfume.contenido4));
        txtlanzamiento.setText(String.valueOf(vperfume.año4));
        txtcasa.setText(vperfume.casa1);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncerrar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxnombre = new javax.swing.JComboBox<>();
        txtprecio = new javax.swing.JTextField();
        txtcontenido = new javax.swing.JTextField();
        txtlanzamiento = new javax.swing.JTextField();
        txtcasa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio (S/)");

        jLabel3.setText("Contenido (ml)");

        jLabel4.setText("Año de lanzamiento");

        jLabel5.setText("Casa");

        cbxnombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxnombreItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(70, 70, 70))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprecio)
                            .addComponent(cbxnombre, 0, 127, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngrabar)
                            .addComponent(btncerrar))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcontenido)
                            .addComponent(txtlanzamiento)
                            .addComponent(txtcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(130, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncerrar)
                    .addComponent(jLabel1)
                    .addComponent(cbxnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngrabar)
                    .addComponent(jLabel2)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxnombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxnombreItemStateChanged
        int opcion = cbxnombre.getSelectedIndex();
         
         switch(opcion){
             case 0: categoria(); break;
             case 1: categoriaUno(); break;
             case 2: categoriaDos(); break;
             case 3: categoriaTres(); break;
             case 4: categoriaCuatro(); break;
             //default: categoria();
         }
    }//GEN-LAST:event_cbxnombreItemStateChanged
    
    //Metodo encargado de guardar contenido a la memoria pasando parametros
    public void guardarDatos(double p, double c, int a, String ca){
        /*this.precio0 = p;
        double contenido0 = c;
        int lanzamiento0 = a;
        String casa0 = ca;
        
        //imprime los datos editados "Prueba"
        System.out.println(this.precio0);*/
        
        vperfume.setPrecio0(p);
        vperfume.setContenido0(c);
        vperfume.setAño0(a);
        vperfume.setCasa0(ca);
        
        System.out.println(p);
    }
    
    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed
    
    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        //se combierte los parametros al tipo de variable del metodo guardarDatos
        /*guardarDatos(
                Double.parseDouble(txtprecio.getText()),
                Double.parseDouble(txtcontenido.getText()),
                Integer.parseInt(txtlanzamiento.getText()),
                txtcasa.getText()
        );*/
        //se cierra el dialogo al guardar
        //dispose();
        String p = txtprecio.getText();
        String c = txtcontenido.getText();
        String a = txtlanzamiento.getText();
        String ca = txtcasa.getText();
        
        double pp = Double.parseDouble(p);
        double cc = Double.parseDouble(c);
        int aa = Integer.parseInt(a);
        String caa = ca;
        guardarDatos(pp, cc, aa, ca);
    }//GEN-LAST:event_btngrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmodificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JComboBox<String> cbxnombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcasa;
    private javax.swing.JTextField txtcontenido;
    private javax.swing.JTextField txtlanzamiento;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
