/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vperfume;
import java.awt.Font;
import java.awt.Label;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

import java.lang.String;
import java.lang.Integer;
/**
 *
 * @author Paola
 */
public class frmvender extends javax.swing.JFrame {
DefaultTableModel model=new DefaultTableModel();

        
    /**
     * Creates new form frmvender
     */
    public frmvender() {
        initComponents();
        muestraNombresCBX();
        inhabilitar();
        titulostabla();
        
        
    }
    
    private void inhabilitar(){
        txtpreciouni.setEnabled(false);
    }
    
    /**/private void titulostabla(){
       this.tabladetalles.setModel(model);
       this.model.addColumn("Nombre Perfume");
       this.model.addColumn("Precio Unitario");
       this.model.addColumn("Cantidad");
       this.model.addColumn("precio");
    }
    
    private void muestraNombresCBX(){
        //declaracionvariables cons=new declaracionvariables();
        cbxnombre.addItem(vperfume.nombre0);
        cbxnombre.addItem(vperfume.nombre1);
        cbxnombre.addItem(vperfume.nombre2);
        cbxnombre.addItem(vperfume.nombre3);
        cbxnombre.addItem(vperfume.nombre4);
    }
    
 
    
    
    private void categoriaCero(){
        txtpreciouni.setText(String.valueOf(vperfume.precio0));
    }    
    private void categoriaUno(){
        txtpreciouni.setText(String.valueOf(vperfume.precio1));
    }    
    private void categoriaDos(){
        txtpreciouni.setText(String.valueOf(vperfume.precio2));
    }    
    private void categoriaTres(){
        txtpreciouni.setText(String.valueOf(vperfume.precio3));
    }    
    private void categoriaCuatro(){
        txtpreciouni.setText(String.valueOf(vperfume.precio4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxnombre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtpreciouni = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnvender = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtimportecompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtimportedescuento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtimportepagar = new javax.swing.JTextField();
        labelpremio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtncliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpreciototal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        cbxnombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxnombreItemStateChanged(evt);
            }
        });
        cbxnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio: s/.");

        jLabel3.setText("Cantidad");

        btnvender.setText("Vender");
        btnvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenderActionPerformed(evt);
            }
        });

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALLE BOLETA"));

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladetalles);

        jLabel4.setText("Importe de Compra: ");

        txtimportecompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimportecompraActionPerformed(evt);
            }
        });

        jLabel5.setText("Importe de Descuento:");

        jLabel6.setText("Importe a Pagar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelpremio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtimportepagar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtimportedescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtimportecompra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtimportecompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtimportedescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelpremio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtimportepagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("N° Cliente:");

        jLabel8.setText("precio total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxnombre, 0, 125, Short.MAX_VALUE)
                    .addComponent(txtpreciouni)
                    .addComponent(txtcantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvender)
                    .addComponent(btncerrar))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(txtpreciototal, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnvender)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpreciouni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btncerrar)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtncliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtpreciototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnombreActionPerformed

    private void cbxnombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxnombreItemStateChanged
        // TODO add your handling code here:
        int nNombreindex = cbxnombre.getSelectedIndex();
         
         switch(nNombreindex){
            case 0: categoriaCero(); break;
            case 1: categoriaUno(); break;
            case 2: categoriaDos(); break;
            case 3: categoriaTres(); break;
            case 4: categoriaCuatro(); break;
            default: categoriaCero();
         }
    }//GEN-LAST:event_cbxnombreItemStateChanged

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenderActionPerformed
        // TODO add your handling code here:
        calcprecioTotal();

        this.model.addRow(new Object[]{this.cbxnombre.getSelectedItem(),
        this.txtpreciouni.getText(),this.txtcantidad.getText(),txtpreciototal.getText()});   
        calcimportecompra();
        calcimportedescuento();
        calcimportepagar();
        
        //System.out.println("cliente"+txtncliente.getText());
        int ncliente=Integer.parseInt(String.valueOf(txtncliente.getText()));
        int ncliensorpresa=vperfume.numeroClienteSorpresa;
        if(ncliente == ncliensorpresa){
            JOptionPane.showMessageDialog(null, "PREMIO SORPRESA : "+vperfume.premioSorpresa);
        }
    }//GEN-LAST:event_btnvenderActionPerformed

    private void calcprecioTotal(){
        
       Double pre=Double.parseDouble(txtpreciouni.getText()); 
       Double cant=Double.parseDouble(txtcantidad.getText());
       Double tot=cant*pre;
       this.txtpreciototal.setText(String.valueOf(tot));
    }
    public void calcimportecompra(){
        Double sumatoria;
        Double sumatoria1=0.0;
        int totalrow=tabladetalles.getRowCount();
        totalrow-=1;
        for(int i =0;i<=(totalrow);i++){
            sumatoria=Double.parseDouble(String.valueOf(tabladetalles.getValueAt(i,3)));
            sumatoria1+=sumatoria;            
        }
        Double imp=sumatoria1+(sumatoria1*0.18);
        txtimportecompra.setText(String.valueOf(imp));
    }
    public void calcimportedescuento(){
        vperfume vperfume=new vperfume();
        
        Double sumatoria;
        Double sumatoria1=0.0;
        
        int totalrow=tabladetalles.getRowCount();
        totalrow-=1;
        for(int i=0;i<=totalrow;i++){
            sumatoria=Double.parseDouble(String.valueOf(tabladetalles.getValueAt(i,2)));
            sumatoria1+=sumatoria;
        }
        String importecompra=(txtimportecompra.getText());
        if(sumatoria1<=5){ 
            Double porc =(vperfume.porcentaje1/100);
            Double descporc=Double.parseDouble(importecompra)*porc;
            txtimportedescuento.setText(String.valueOf(descporc));
        }
        if(sumatoria1>=6 && sumatoria1<=10){
            Double porc =(vperfume.porcentaje2/100);
            Double descporc=Double.parseDouble(importecompra)*porc;
            txtimportedescuento.setText(String.valueOf(descporc));
        }
        if(sumatoria1>=11 && sumatoria1<=15){
            Double porc =(vperfume.porcentaje3/100);
            Double descporc=Double.parseDouble(importecompra)*porc;
            txtimportedescuento.setText(String.valueOf(descporc));
        }
        if(sumatoria1>=16){
            Double porc =(vperfume.porcentaje4/100);
            Double descporc=Double.parseDouble(importecompra)*porc;
            txtimportedescuento.setText(String.valueOf(descporc));
        }
    }
    
    private void calcimportepagar(){
       String impcompra= txtimportecompra.getText();
       String impdescuento= txtimportedescuento.getText();
       Double importepagar=(Double.parseDouble(impcompra))+(Double.parseDouble(impdescuento));
       txtimportepagar.setText(String.valueOf(importepagar));
       
       int importeobsequi = vperfume.importeMinimoObsequiable ;
       
       if(importepagar >= importeobsequi){
           JOptionPane.showMessageDialog(null, "SE GANO : "+vperfume.obsequio);
       }
       
    }
    
    public class MessageDialog {
    
    }
    private void txtimportecompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimportecompraActionPerformed
        // TODO add your handling ucode here:        
    }//GEN-LAST:event_txtimportecompraActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmvender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmvender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmvender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmvender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmvender().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnvender;
    private javax.swing.JComboBox<String> cbxnombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelpremio;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtimportecompra;
    private javax.swing.JTextField txtimportedescuento;
    private javax.swing.JTextField txtimportepagar;
    private javax.swing.JTextField txtncliente;
    private javax.swing.JTextField txtpreciototal;
    private javax.swing.JTextField txtpreciouni;
    // End of variables declaration//GEN-END:variables
}
