/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perfumeria;
import java.awt.event.*;
//import perfumeria.declaracionvariables;
/**
 *
 * @author Paola
 */
public class ConsultarPerfume extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarPerfume
     */
    
    
    
    public ConsultarPerfume() {
        initComponents();
        combonombre();
        
    }
   
    public void combonombre(){
        //declaracionvariables cons=new declaracionvariables();
        
        cbonombre.addItem(declaracionvariables.nombre0);
        cbonombre.addItem(declaracionvariables.nombre1);
        cbonombre.addItem(declaracionvariables.nombre2);
        cbonombre.addItem(declaracionvariables.nombre3);
        cbonombre.addItem(declaracionvariables.nombre4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new java.awt.Label();
        añolanzamiento = new java.awt.Label();
        precio = new java.awt.Label();
        contenido1 = new java.awt.Label();
        casa = new java.awt.Label();
        cbonombre = new java.awt.Choice();
        txtprecio = new java.awt.TextField();
        txtcontenido = new java.awt.TextField();
        txtañolanzamiento = new java.awt.TextField();
        txtcasa = new java.awt.TextField();
        btncerrar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.setText("Nombre");

        añolanzamiento.setText("Año de Lanzamiento");

        precio.setText("Precio (S/)");

        contenido1.setText("Contenido (ml)");

        casa.setText("Casa");

        cbonombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbonombreItemStateChanged(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        btncerrar.setLabel("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contenido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añolanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbonombre, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtañolanzamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtañolanzamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(añolanzamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:        
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    public void actionPerformed(java.awt.event.ActionEvent evt) { 
        
    }
    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_txtprecioActionPerformed

    private void cbonombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbonombreItemStateChanged
        // TODO add your handling code here:
        String nombre = cbonombre.getSelectedItem();
                txtprecio.setEnabled(false);
                txtcontenido.setEnabled(false);
                txtañolanzamiento.setEnabled(false);
                txtcasa.setEnabled(false);
                
            if(nombre==declaracionvariables.nombre0)
                {  
                  this.txtprecio.setText(String.valueOf(declaracionvariables.precio0));
                  this.txtcontenido.setText(String.valueOf(declaracionvariables.contenido0));
                  this.txtañolanzamiento.setText(String.valueOf(declaracionvariables.año0));
                  this.txtcasa.setText(declaracionvariables.casa0);
                }
            else if(nombre==declaracionvariables.nombre1)
                {  
                  this.txtprecio.setText(String.valueOf(declaracionvariables.precio1));
                  this.txtcontenido.setText(String.valueOf(declaracionvariables.contenido1));
                  this.txtañolanzamiento.setText(String.valueOf(declaracionvariables.año1));
                  this.txtcasa.setText(declaracionvariables.casa1);
                }
            else if(nombre==declaracionvariables.nombre2)
                {  
                  this.txtprecio.setText(String.valueOf(declaracionvariables.precio2));
                  this.txtcontenido.setText(String.valueOf(declaracionvariables.contenido2));
                  this.txtañolanzamiento.setText(String.valueOf(declaracionvariables.año2));
                  this.txtcasa.setText(declaracionvariables.casa1);
                }
            else if(nombre==declaracionvariables.nombre3)
                {  
                  this.txtprecio.setText(String.valueOf(declaracionvariables.precio3));
                  this.txtcontenido.setText(String.valueOf(declaracionvariables.contenido3));
                  this.txtañolanzamiento.setText(String.valueOf(declaracionvariables.año3));
                  this.txtcasa.setText(declaracionvariables.casa1);
                }
            else if(nombre==declaracionvariables.nombre4)
                {  
                  this.txtprecio.setText(String.valueOf(declaracionvariables.precio4));
                  this.txtcontenido.setText(String.valueOf(declaracionvariables.contenido4));
                  this.txtañolanzamiento.setText(String.valueOf(declaracionvariables.año4));
                  this.txtcasa.setText(declaracionvariables.casa1);
                }
                       
    }//GEN-LAST:event_cbonombreItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPerfume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label añolanzamiento;
    private java.awt.Button btncerrar;
    private java.awt.Label casa;
    private java.awt.Choice cbonombre;
    private java.awt.Label contenido1;
    private java.awt.Label nombre;
    private java.awt.Label precio;
    private java.awt.TextField txtañolanzamiento;
    private java.awt.TextField txtcasa;
    private java.awt.TextField txtcontenido;
    private java.awt.TextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
